fixtures:
  repositories:
    'redis': 'git://github.com/fsalum/puppet-redis.git'
    'nginx': 'git://github.com/jfryman/puppet-nginx.git'
    'git': 'git://github.com/puppetlabs/puppetlabs-git.git'
    'mysql': 'git://github.com/puppetlabs/puppetlabs-mysql.git'
    'ruby': 'git://github.com/puppetlabs/puppetlabs-ruby.git'
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    'apt': 'git://github.com/puppetlabs/puppetlabs-apt.git'
  symlinks:
    "gitlab_requirements": "#{source_dir}"
